In [1]:
import pandas as pd
import numpy as np

In [2]:
Data=pd.read_csv('home.txt',names=['size','bedroom','price'])

In [7]:
X[0]

array([1.        , 0.71354   , 0.50913933, 0.36329128, 0.25922286,
       0.18496588, 0.13198055, 0.0941734 , 0.06719649, 0.04794738,
       0.03421238])

In [12]:
X=Phi[:,1:]

In [9]:
X=(X-np.mean(X,axis=0))/np.std(X)

In [14]:
X=np.concatenate((np.ones((X.shape[0],1)),X),axis=1)

In [15]:
np.max(X)

1.0

In [13]:
X=(X-np.mean(X,axis=0))/(np.max(X,axis=0)-np.min(X,axis=0))

In [16]:
y_train.shape

(80,)

In [17]:
X_train=X[:50]
Y_train=y_train[:50]

In [18]:
Y_train

array([5.9398, 6.3081, 4.0088, 5.9793, 6.1301, 5.9084, 6.4621, 6.09  ,
       6.6191, 6.004 , 5.906 , 5.9771, 5.5281, 6.3495, 6.2893, 6.0223,
       5.8806, 6.1411, 4.5844, 5.9732, 5.987 , 6.1284, 6.5953, 5.9727,
       6.0196, 6.4035, 6.0553, 6.3953, 3.9168, 5.8992, 6.0688, 6.1484,
       6.084 , 5.9328, 5.9052, 6.2054, 6.0954, 6.373 , 5.9788, 6.1935,
       5.9829, 5.9846, 5.9129, 5.9672, 6.6484, 5.8712, 6.1855, 5.9808,
       6.441 , 6.0137])

In [19]:
X_test=X[50:]
Y_test=y_train[50:]

In [20]:
alpha = 0.1
iters = 1000


In [127]:
X_train.shape

(50, 11)

In [128]:
X_train.shape

(50, 11)

In [21]:
def gradient_descent(X,y,alpha,iters):
    theta=np.zeros((1,11))
    for i in range(iters):
        forward_ans=np.dot(X,theta.T)
        forward_ans=forward_ans.ravel()
        error=forward_ans-y
        print(np.sum(error))
        theta=theta-alpha*1/len(X)*np.dot(error.T,X)
    return theta

In [214]:
def gradientDescent(X,y,iters,alpha):
    theta=np.zeros((1,3))
    for i in range(iters):
        theta = theta - (alpha/len(X)) * np.sum(X * (X @ theta.T - y), axis=0)
        print(theta)

    
    return theta


In [22]:
theta=gradient_descent(X_train,Y_train,0.1,2000)

-299.4479
-269.49527352197316
-242.5406978476391
-218.28400831545548
-196.45509617838692
-176.81089891328205
-159.1326919162504
-143.22365140340852
-128.90666135864757
-116.0223400897078
-104.42726440113401
-93.99237159490269
-84.60152149119922
-76.15020244506296
-68.54436693928734
-61.69938377793619
-55.539095204213616
-49.994968435683134
-45.00533216199694
-40.51468949710108
-36.47309972987229
-32.83562198381494
-29.561814586343832
-26.615284568991022
-23.963282278517703
-21.57633658161382
-19.427926598228662
-17.49418630563723
-15.753638721645501
-14.186956704955227
-12.77674770731856
-11.50736007901983
-10.364708769401215
-9.33611848027714
-8.41018252456627
-7.576635817479888
-6.826240585089511
-6.150683516809236
-5.542483215851708
-4.994906916468565
-4.501895540047303
-4.057996255057815
-3.658301789456709
-3.2983958194008234
-2.974303825828495
-2.68244887139527
-2.4196118050768605
-2.182895451088028
-1.969692383162585
-1.7776559251883355
-1.6046740551419565
-1.4488459216163068
-1.

0.0010612038414641312
0.0010600366211597212
0.0010588704151213157
0.0010577052244804541
0.0010565410502745287
0.0010553778935551428
0.0010542157553801168
0.0010530546367504279
0.0010518945387087975
0.0010507354622819598
0.0010495774084176013
0.0010484203780829482
0.0010472643722621022
0.0010461093919231779
0.0010449554379543535
0.0010438025113344018
0.0010426506128928814
0.0010414997435996831
0.0010403499043021291
0.0010392010959026088
0.0010380533192591024
0.0010369065752064976
0.0010357608645787941
0.0010346161881993332
0.00103347254687991
0.0010323299414189968
0.0010311883726150661
0.0010300478412577085
0.0010289083480814476
0.001027769893826136
0.0010266324792813641
0.0010254961051097133
0.0010243607721087677
0.001023226480909134
0.001022093232241783
0.0010209610267781777
0.0010198298651835636
0.0010186997481684834
0.0010175706763129178
0.001016442650300764
0.0010153156706960154
0.0010141897381976683
0.0010130648533430708
0.0010119410167681586
0.0010108182290609058
0.00100969649075

In [23]:
theta

array([[ 5.99643928, -0.12583872,  0.97139066, -0.31050448, -0.31567211,
        -0.62275657, -0.56944166, -0.4851415 , -0.29049148, -0.06239881,
         0.19909715]])

In [107]:
theta=np.zeros((1,3))

In [53]:
forward_ans=np.dot(X_train,theta.T)

In [218]:
forward_ans.shape

(50, 1)

In [113]:
np.dot(X_train.T,error).shape

(3, 1)

In [140]:
y_pred=np.dot(X_test,theta.T)

In [141]:
y_pred.shape

(30, 1)

In [142]:
Y_test.shape

(30,)

In [143]:
y_pred

array([[5.96106128],
       [6.14194547],
       [6.00792524],
       [6.12346757],
       [6.05184888],
       [6.11274853],
       [6.00499987],
       [6.05706311],
       [6.00490873],
       [6.07944752],
       [6.03696677],
       [6.10581717],
       [6.01941373],
       [6.20794799],
       [6.22284516],
       [6.01048338],
       [6.09052297],
       [6.06264627],
       [6.04668104],
       [5.28515883],
       [6.00684165],
       [6.0644225 ],
       [6.07270691],
       [5.79989373],
       [6.11780277],
       [6.12402725],
       [6.072292  ],
       [6.1143144 ],
       [6.08067071],
       [5.17985754]])

In [144]:
Y_test

array([6.4799, 6.0513, 5.8961, 6.0721, 5.9499, 6.1684, 5.9885, 5.9963,
       5.9994, 5.993 , 6.0202, 5.8781, 5.9027, 6.34  , 6.365 , 6.0114,
       6.0176, 6.0311, 6.0857, 4.1137, 6.0038, 5.9192, 6.4699, 5.9205,
       5.9122, 6.0103, 5.947 , 5.9135, 5.9763, 3.8991])

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
N=80
M=10

datas = pd.read_csv(r"Gaussian_noise.csv")
X = datas.iloc[:, 0].values
x_test=X[N:100]
y=np.zeros([N,1]);
y = datas.iloc[:, 1].values
x_train=X[:N]
y_train= y[:N]


plt.scatter(X, y)
plt.xlabel('x')
plt.ylabel('y')

Phi=np.zeros([N,M+1])

for n in range (N) :
    for m in range (M+1) :
        Phi[n][m]=X[n]**m  
w = [1 for i in range(0,M+1)]

Phi_T=np.transpose(Phi)

pinv=np.linalg.inv(np.dot(Phi_T,Phi))
w= np.dot(np.dot(pinv,Phi_T),y_train).reshape(-1,1)

print(w)



[[ 5.99923533]
 [-0.31387725]
 [ 0.14621896]
 [ 2.87722335]
 [-2.25870305]
 [-6.36905877]
 [ 6.29269731]
 [ 2.63565487]
 [-4.0646641 ]
 [ 0.94811112]
 [ 0.02963141]]


In [4]:
Phi.shape

(80, 11)

In [5]:
X=Phi

In [6]:
X.shape

(80, 11)