In [1]:
import numpy as np

In [6]:
from sklearn import datasets

In [7]:
iris = datasets.load_iris()


In [19]:
X=iris.data[:,:2]
Y=(iris.target != 0) * 1

In [21]:
Y=np.where(Y!=0,1,0)

In [57]:
X.shape

(150, 2)

In [62]:
X_train=X[:125]
Y_train=Y[:125]
X_test=X[125:]
Y_test=Y[125:]

In [65]:
class LR:
    def __init__(self,lr=0.01,num_iter=10000,fit_intercept=True):
        self.lr=lr
        self.num_iter=num_iter
        self.fit_intercept=fit_intercept
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    def fit(self,X):
        intercept=np.ones((X.shape[0],1))
        return np.concatenate((intercept,X),axis=1)
    def train(self,X,y):
        if(self.fit_intercept):
            X=self.fit(X);
        self.theta=np.zeros(X.shape[1])
        for i in range(self.num_iter):
            z=np.dot(X,self.theta)
            h=self.sigmoid(z)
            gradient=np.dot(X.T,h-y)/X.shape[0]
            self.theta-=self.lr*gradient
    def predict(self,X):
        if(self.fit_intercept):
            X=self.fit(X);
        return self.sigmoid(np.dot(X,self.theta))
    def class_predictor(self,X):
        return np.where(self.predict(X)>=0.5,1,0)            

In [66]:
model=LR(0.1,10000)

In [67]:
model.train(X_train,Y_train)

In [68]:
model.theta

array([-3.04217021,  5.94939548, -9.40698743])

In [69]:
model.class_predictor(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [70]:
Y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [71]:
X_train

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.1],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [72]:
np.max(X_train,axis=0)

array([7.7, 4.4])

In [77]:
np.max(X_train/np.max(X_train,axis=0),axis=0)

array([1., 1.])